services:
  flask_app:
    build: .
    container_name: conta_check_status_container
    ports:
      - "5000:5000"
    volumes:
      #- ./app:/app               # c√≥digo (puede ser solo para desarrollo)
      - ./config:/config         # configs externas
      - ./logs:/logs             # logs accesibles
      - ./data:/data             # datos persistentes
    environment:
      - FLASK_ENV=production
