services:
  app:
    build: .
    container_name: conta_check_status
    volumes:
      - ./config:/config
      - ../conta_archive/archive/archive_main:/data_main
      - ../conta_archive/archive/archive_support:/data_support
      - ../conta_archive/archive/archive_periodic:/data_periodic
      - ./log:/log
    ports:
      - "9000:9000"
    restart: unless-stopped

