services:
  app:
    build: .
    container_name: conta_check_status
    volumes:
      - ./config:/app/config
      - ../conta_archive/archive/archive_main:/data
      - ./log:/log
    ports:
      - "9000:9000"
    restart: unless-stopped

